{
 "title": "DockerMonitor",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "USO TOTAL CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=~\"/docker/.*\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "USO DE RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id=~\"/docker/.*\"}",
     "legendFormat": "{{name}} - {{id}}"
    }
   ]
  },
  {
   "title": "USO TOTAL CPU POR NUCLEO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{id=~\"/docker/.*\"}[1m])",
     "legendFormat": "{{name}} - {{cpu}}"
    }
   ]
  },
  {
   "title": "Container Start Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(container_start_time_seconds{id=~\"/docker/.*\"}) * 1000",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}