version: '3.3'
services:
  prometheus:
    image: prom/prometheus:v2.26.0
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - back-end
    depends_on:
      - cadvisor

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.37.5
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      # - /:/rootfs:ro # LINUX
      - /var/run/docker.sock:/var/run/docker.sock:ro # MAC
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - back-end
  
  grafana:
    image: grafana/grafana:7.4.3
    # environment:
    #   GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,frser-sqlite-datasource"
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - back-end

networks: 
  back-end:
    driver: bridge

volumes:
  grafana:
